// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "PE27.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic PE27::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic PE27::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> PE27::ap_ST_fsm_state1 = "1";
const sc_lv<7> PE27::ap_ST_fsm_state2 = "10";
const sc_lv<7> PE27::ap_ST_fsm_state3 = "100";
const sc_lv<7> PE27::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<7> PE27::ap_ST_fsm_pp0_stage1 = "10000";
const sc_lv<7> PE27::ap_ST_fsm_pp0_stage2 = "100000";
const sc_lv<7> PE27::ap_ST_fsm_state12 = "1000000";
const bool PE27::ap_const_boolean_1 = true;
const sc_lv<32> PE27::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> PE27::ap_const_lv32_4 = "100";
const bool PE27::ap_const_boolean_0 = false;
const sc_lv<1> PE27::ap_const_lv1_0 = "0";
const sc_lv<32> PE27::ap_const_lv32_6 = "110";
const sc_lv<32> PE27::ap_const_lv32_1 = "1";
const sc_lv<32> PE27::ap_const_lv32_2 = "10";
const sc_lv<32> PE27::ap_const_lv32_3 = "11";
const sc_lv<1> PE27::ap_const_lv1_1 = "1";
const sc_lv<32> PE27::ap_const_lv32_5 = "101";
const sc_lv<31> PE27::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<96> PE27::ap_const_lv96_0 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<31> PE27::ap_const_lv31_1 = "1";
const sc_lv<96> PE27::ap_const_lv96_1 = "1";

PE27::PE27(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Systolic_Array_CodEe_U221 = new Systolic_Array_CodEe<1,4,32,32,32>("Systolic_Array_CodEe_U221");
    Systolic_Array_CodEe_U221->clk(ap_clk);
    Systolic_Array_CodEe_U221->reset(ap_rst);
    Systolic_Array_CodEe_U221->din0(ap_phi_mux_tmp_phi_fu_252_p4);
    Systolic_Array_CodEe_U221->din1(tmp_4_i_i_i_reg_395);
    Systolic_Array_CodEe_U221->ce(grp_fu_260_ce);
    Systolic_Array_CodEe_U221->dout(grp_fu_260_p2);
    Systolic_Array_CoeOg_U222 = new Systolic_Array_CoeOg<1,2,32,32,32>("Systolic_Array_CoeOg_U222");
    Systolic_Array_CoeOg_U222->clk(ap_clk);
    Systolic_Array_CoeOg_U222->reset(ap_rst);
    Systolic_Array_CoeOg_U222->din0(tmp_47_reg_390);
    Systolic_Array_CoeOg_U222->din1(tmp_48_reg_385);
    Systolic_Array_CoeOg_U222->ce(grp_fu_265_ce);
    Systolic_Array_CoeOg_U222->dout(grp_fu_265_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_In_inter_1_2_blk_n);
    sensitive << ( In_inter_1_2_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_In_inter_1_2_read);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_In_inter_1_3_blk_n);
    sensitive << ( In_inter_1_3_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_In_inter_1_3_din);
    sensitive << ( In_inter_1_2_dout );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( ap_block_pp0_stage1_01001 );

    SC_METHOD(thread_In_inter_1_3_write);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_O_inter_1_2_blk_n);
    sensitive << ( O_inter_1_2_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_O_inter_1_2_din);
    sensitive << ( O_inter_1_2_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_reg_247 );

    SC_METHOD(thread_O_inter_1_2_write);
    sensitive << ( O_inter_1_2_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_O_temp_10_fu_335_p3);
    sensitive << ( tmp_reg_247 );
    sensitive << ( and_ln130_reg_357 );
    sensitive << ( grp_fu_260_p2 );

    SC_METHOD(thread_W_inter_1_2_blk_n);
    sensitive << ( W_inter_1_2_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_W_inter_1_2_read);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_W_inter_2_2_blk_n);
    sensitive << ( W_inter_2_2_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_W_inter_2_2_din);
    sensitive << ( W_inter_1_2_dout );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( ap_block_pp0_stage1_01001 );

    SC_METHOD(thread_W_inter_2_2_write);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_add_ln119_fu_318_p2);
    sensitive << ( col_0_i_i_i_reg_225 );

    SC_METHOD(thread_add_ln122_fu_329_p2);
    sensitive << ( ap_phi_mux_indvar_flatten13_phi_fu_240_p4 );

    SC_METHOD(thread_add_ln207_1_loc_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_1_loc_empty_n );

    SC_METHOD(thread_add_ln207_1_loc_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_1_loc_out_full_n );

    SC_METHOD(thread_add_ln207_1_loc_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_dout );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_add_ln207_1_loc_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_add_ln207_1_loc_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_add_ln207_3_loc_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );

    SC_METHOD(thread_add_ln207_3_loc_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_and_ln130_fu_281_p2);
    sensitive << ( icmp_ln130_fu_269_p2 );
    sensitive << ( icmp_ln130_10_fu_275_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_01001);
    sensitive << ( W_inter_1_2_empty_n );
    sensitive << ( In_inter_1_2_empty_n );
    sensitive << ( W_inter_2_2_full_n );
    sensitive << ( In_inter_1_3_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_ap_block_pp0_stage1_11001);
    sensitive << ( W_inter_1_2_empty_n );
    sensitive << ( In_inter_1_2_empty_n );
    sensitive << ( W_inter_2_2_full_n );
    sensitive << ( In_inter_1_3_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( W_inter_1_2_empty_n );
    sensitive << ( In_inter_1_2_empty_n );
    sensitive << ( W_inter_2_2_full_n );
    sensitive << ( In_inter_1_3_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state11_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter0);
    sensitive << ( W_inter_1_2_empty_n );
    sensitive << ( In_inter_1_2_empty_n );
    sensitive << ( W_inter_2_2_full_n );
    sensitive << ( In_inter_1_3_full_n );
    sensitive << ( icmp_ln122_reg_376 );

    SC_METHOD(thread_ap_block_state6_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state8_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state9_pp0_stage2_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( icmp_ln122_fu_324_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln119_fu_313_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten13_phi_fu_240_p4);
    sensitive << ( icmp_ln122_reg_376 );
    sensitive << ( indvar_flatten13_reg_236 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( add_ln122_reg_380 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_tmp_phi_fu_252_p4);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_reg_247 );
    sensitive << ( icmp_ln122_reg_376_pp0_iter2_reg );
    sensitive << ( O_temp_10_fu_335_p3 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_bound4_fu_303_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( bound4_fu_303_p00 );

    SC_METHOD(thread_bound4_fu_303_p00);
    sensitive << ( bound_fu_290_p2 );

    SC_METHOD(thread_bound4_fu_303_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( bound4_fu_303_p10 );

    SC_METHOD(thread_bound4_fu_303_p10);
    sensitive << ( p_chin_read_reg_347 );

    SC_METHOD(thread_bound4_fu_303_p2);
    sensitive << ( bound4_fu_303_p0 );
    sensitive << ( bound4_fu_303_p1 );

    SC_METHOD(thread_bound_fu_290_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( cast_fu_287_p1 );

    SC_METHOD(thread_bound_fu_290_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( cast_fu_287_p1 );

    SC_METHOD(thread_bound_fu_290_p2);
    sensitive << ( bound_fu_290_p0 );
    sensitive << ( bound_fu_290_p1 );

    SC_METHOD(thread_cast_fu_287_p1);
    sensitive << ( p_k_read_reg_352 );

    SC_METHOD(thread_col_0_i_i_i_cast_fu_309_p1);
    sensitive << ( col_0_i_i_i_reg_225 );

    SC_METHOD(thread_grp_fu_260_ce);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_grp_fu_265_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_icmp_ln119_fu_313_p2);
    sensitive << ( p_c_read_reg_342 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_0_i_i_i_cast_fu_309_p1 );

    SC_METHOD(thread_icmp_ln122_fu_324_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( bound4_reg_362 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_indvar_flatten13_phi_fu_240_p4 );

    SC_METHOD(thread_icmp_ln130_10_fu_275_p2);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_dout );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_dout );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_icmp_ln130_fu_269_p2);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_dout );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_dout );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln119_fu_313_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_p_c_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_c_out_full_n );

    SC_METHOD(thread_p_c_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_dout );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_c_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_c_s_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_c_s_empty_n );

    SC_METHOD(thread_p_c_s_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_chin_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_chin_out_full_n );

    SC_METHOD(thread_p_chin_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_dout );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_chin_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_chin_s_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_chin_s_empty_n );

    SC_METHOD(thread_p_chin_s_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_chout_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_chout_out_full_n );

    SC_METHOD(thread_p_chout_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_dout );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_chout_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_chout_s_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_chout_s_empty_n );

    SC_METHOD(thread_p_chout_s_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_k_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_k_out_full_n );

    SC_METHOD(thread_p_k_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_dout );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_k_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_k_s_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_k_s_empty_n );

    SC_METHOD(thread_p_k_s_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_r_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_r_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_dout );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_r_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_p_r_s_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_r_s_empty_n );

    SC_METHOD(thread_p_r_s_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln207_3_loc_empty_n );
    sensitive << ( add_ln207_1_loc_empty_n );
    sensitive << ( O_inter_1_2_full_n );
    sensitive << ( p_c_s_empty_n );
    sensitive << ( p_chin_s_empty_n );
    sensitive << ( p_chout_s_empty_n );
    sensitive << ( p_k_s_empty_n );
    sensitive << ( p_r_s_empty_n );
    sensitive << ( add_ln207_1_loc_out_full_n );
    sensitive << ( p_c_out_full_n );
    sensitive << ( p_chin_out_full_n );
    sensitive << ( p_chout_out_full_n );
    sensitive << ( p_k_out_full_n );
    sensitive << ( p_r_out_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln119_fu_313_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln122_fu_324_p2 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "PE27_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, W_inter_1_2_dout, "(port)W_inter_1_2_dout");
    sc_trace(mVcdFile, W_inter_1_2_empty_n, "(port)W_inter_1_2_empty_n");
    sc_trace(mVcdFile, W_inter_1_2_read, "(port)W_inter_1_2_read");
    sc_trace(mVcdFile, In_inter_1_2_dout, "(port)In_inter_1_2_dout");
    sc_trace(mVcdFile, In_inter_1_2_empty_n, "(port)In_inter_1_2_empty_n");
    sc_trace(mVcdFile, In_inter_1_2_read, "(port)In_inter_1_2_read");
    sc_trace(mVcdFile, W_inter_2_2_din, "(port)W_inter_2_2_din");
    sc_trace(mVcdFile, W_inter_2_2_full_n, "(port)W_inter_2_2_full_n");
    sc_trace(mVcdFile, W_inter_2_2_write, "(port)W_inter_2_2_write");
    sc_trace(mVcdFile, In_inter_1_3_din, "(port)In_inter_1_3_din");
    sc_trace(mVcdFile, In_inter_1_3_full_n, "(port)In_inter_1_3_full_n");
    sc_trace(mVcdFile, In_inter_1_3_write, "(port)In_inter_1_3_write");
    sc_trace(mVcdFile, add_ln207_3_loc_dout, "(port)add_ln207_3_loc_dout");
    sc_trace(mVcdFile, add_ln207_3_loc_empty_n, "(port)add_ln207_3_loc_empty_n");
    sc_trace(mVcdFile, add_ln207_3_loc_read, "(port)add_ln207_3_loc_read");
    sc_trace(mVcdFile, add_ln207_1_loc_dout, "(port)add_ln207_1_loc_dout");
    sc_trace(mVcdFile, add_ln207_1_loc_empty_n, "(port)add_ln207_1_loc_empty_n");
    sc_trace(mVcdFile, add_ln207_1_loc_read, "(port)add_ln207_1_loc_read");
    sc_trace(mVcdFile, O_inter_1_2_din, "(port)O_inter_1_2_din");
    sc_trace(mVcdFile, O_inter_1_2_full_n, "(port)O_inter_1_2_full_n");
    sc_trace(mVcdFile, O_inter_1_2_write, "(port)O_inter_1_2_write");
    sc_trace(mVcdFile, p_c_s_dout, "(port)p_c_s_dout");
    sc_trace(mVcdFile, p_c_s_empty_n, "(port)p_c_s_empty_n");
    sc_trace(mVcdFile, p_c_s_read, "(port)p_c_s_read");
    sc_trace(mVcdFile, p_chin_s_dout, "(port)p_chin_s_dout");
    sc_trace(mVcdFile, p_chin_s_empty_n, "(port)p_chin_s_empty_n");
    sc_trace(mVcdFile, p_chin_s_read, "(port)p_chin_s_read");
    sc_trace(mVcdFile, p_chout_s_dout, "(port)p_chout_s_dout");
    sc_trace(mVcdFile, p_chout_s_empty_n, "(port)p_chout_s_empty_n");
    sc_trace(mVcdFile, p_chout_s_read, "(port)p_chout_s_read");
    sc_trace(mVcdFile, p_k_s_dout, "(port)p_k_s_dout");
    sc_trace(mVcdFile, p_k_s_empty_n, "(port)p_k_s_empty_n");
    sc_trace(mVcdFile, p_k_s_read, "(port)p_k_s_read");
    sc_trace(mVcdFile, p_r_s_dout, "(port)p_r_s_dout");
    sc_trace(mVcdFile, p_r_s_empty_n, "(port)p_r_s_empty_n");
    sc_trace(mVcdFile, p_r_s_read, "(port)p_r_s_read");
    sc_trace(mVcdFile, add_ln207_1_loc_out_din, "(port)add_ln207_1_loc_out_din");
    sc_trace(mVcdFile, add_ln207_1_loc_out_full_n, "(port)add_ln207_1_loc_out_full_n");
    sc_trace(mVcdFile, add_ln207_1_loc_out_write, "(port)add_ln207_1_loc_out_write");
    sc_trace(mVcdFile, p_c_out_din, "(port)p_c_out_din");
    sc_trace(mVcdFile, p_c_out_full_n, "(port)p_c_out_full_n");
    sc_trace(mVcdFile, p_c_out_write, "(port)p_c_out_write");
    sc_trace(mVcdFile, p_chin_out_din, "(port)p_chin_out_din");
    sc_trace(mVcdFile, p_chin_out_full_n, "(port)p_chin_out_full_n");
    sc_trace(mVcdFile, p_chin_out_write, "(port)p_chin_out_write");
    sc_trace(mVcdFile, p_chout_out_din, "(port)p_chout_out_din");
    sc_trace(mVcdFile, p_chout_out_full_n, "(port)p_chout_out_full_n");
    sc_trace(mVcdFile, p_chout_out_write, "(port)p_chout_out_write");
    sc_trace(mVcdFile, p_k_out_din, "(port)p_k_out_din");
    sc_trace(mVcdFile, p_k_out_full_n, "(port)p_k_out_full_n");
    sc_trace(mVcdFile, p_k_out_write, "(port)p_k_out_write");
    sc_trace(mVcdFile, p_r_out_din, "(port)p_r_out_din");
    sc_trace(mVcdFile, p_r_out_full_n, "(port)p_r_out_full_n");
    sc_trace(mVcdFile, p_r_out_write, "(port)p_r_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, W_inter_1_2_blk_n, "W_inter_1_2_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, icmp_ln122_reg_376, "icmp_ln122_reg_376");
    sc_trace(mVcdFile, In_inter_1_2_blk_n, "In_inter_1_2_blk_n");
    sc_trace(mVcdFile, W_inter_2_2_blk_n, "W_inter_2_2_blk_n");
    sc_trace(mVcdFile, In_inter_1_3_blk_n, "In_inter_1_3_blk_n");
    sc_trace(mVcdFile, add_ln207_3_loc_blk_n, "add_ln207_3_loc_blk_n");
    sc_trace(mVcdFile, add_ln207_1_loc_blk_n, "add_ln207_1_loc_blk_n");
    sc_trace(mVcdFile, O_inter_1_2_blk_n, "O_inter_1_2_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, p_c_s_blk_n, "p_c_s_blk_n");
    sc_trace(mVcdFile, p_chin_s_blk_n, "p_chin_s_blk_n");
    sc_trace(mVcdFile, p_chout_s_blk_n, "p_chout_s_blk_n");
    sc_trace(mVcdFile, p_k_s_blk_n, "p_k_s_blk_n");
    sc_trace(mVcdFile, p_r_s_blk_n, "p_r_s_blk_n");
    sc_trace(mVcdFile, add_ln207_1_loc_out_blk_n, "add_ln207_1_loc_out_blk_n");
    sc_trace(mVcdFile, p_c_out_blk_n, "p_c_out_blk_n");
    sc_trace(mVcdFile, p_chin_out_blk_n, "p_chin_out_blk_n");
    sc_trace(mVcdFile, p_chout_out_blk_n, "p_chout_out_blk_n");
    sc_trace(mVcdFile, p_k_out_blk_n, "p_k_out_blk_n");
    sc_trace(mVcdFile, p_r_out_blk_n, "p_r_out_blk_n");
    sc_trace(mVcdFile, indvar_flatten13_reg_236, "indvar_flatten13_reg_236");
    sc_trace(mVcdFile, tmp_reg_247, "tmp_reg_247");
    sc_trace(mVcdFile, p_c_read_reg_342, "p_c_read_reg_342");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, p_chin_read_reg_347, "p_chin_read_reg_347");
    sc_trace(mVcdFile, p_k_read_reg_352, "p_k_read_reg_352");
    sc_trace(mVcdFile, and_ln130_fu_281_p2, "and_ln130_fu_281_p2");
    sc_trace(mVcdFile, and_ln130_reg_357, "and_ln130_reg_357");
    sc_trace(mVcdFile, bound4_fu_303_p2, "bound4_fu_303_p2");
    sc_trace(mVcdFile, bound4_reg_362, "bound4_reg_362");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln119_fu_313_p2, "icmp_ln119_fu_313_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln119_fu_318_p2, "add_ln119_fu_318_p2");
    sc_trace(mVcdFile, add_ln119_reg_371, "add_ln119_reg_371");
    sc_trace(mVcdFile, icmp_ln122_fu_324_p2, "icmp_ln122_fu_324_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter1, "ap_block_state7_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter2, "ap_block_state10_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln122_reg_376_pp0_iter1_reg, "icmp_ln122_reg_376_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln122_reg_376_pp0_iter2_reg, "icmp_ln122_reg_376_pp0_iter2_reg");
    sc_trace(mVcdFile, add_ln122_fu_329_p2, "add_ln122_fu_329_p2");
    sc_trace(mVcdFile, add_ln122_reg_380, "add_ln122_reg_380");
    sc_trace(mVcdFile, tmp_48_reg_385, "tmp_48_reg_385");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter0, "ap_block_state5_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage1_iter1, "ap_block_state8_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage1_iter2, "ap_block_state11_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, tmp_47_reg_390, "tmp_47_reg_390");
    sc_trace(mVcdFile, grp_fu_265_p2, "grp_fu_265_p2");
    sc_trace(mVcdFile, tmp_4_i_i_i_reg_395, "tmp_4_i_i_i_reg_395");
    sc_trace(mVcdFile, O_temp_10_fu_335_p3, "O_temp_10_fu_335_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage2_iter0, "ap_block_state6_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage2_iter1, "ap_block_state9_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, col_0_i_i_i_reg_225, "col_0_i_i_i_reg_225");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten13_phi_fu_240_p4, "ap_phi_mux_indvar_flatten13_phi_fu_240_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_tmp_phi_fu_252_p4, "ap_phi_mux_tmp_phi_fu_252_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage1_01001, "ap_block_pp0_stage1_01001");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, icmp_ln130_fu_269_p2, "icmp_ln130_fu_269_p2");
    sc_trace(mVcdFile, icmp_ln130_10_fu_275_p2, "icmp_ln130_10_fu_275_p2");
    sc_trace(mVcdFile, bound_fu_290_p0, "bound_fu_290_p0");
    sc_trace(mVcdFile, cast_fu_287_p1, "cast_fu_287_p1");
    sc_trace(mVcdFile, bound_fu_290_p1, "bound_fu_290_p1");
    sc_trace(mVcdFile, bound_fu_290_p2, "bound_fu_290_p2");
    sc_trace(mVcdFile, bound4_fu_303_p0, "bound4_fu_303_p0");
    sc_trace(mVcdFile, bound4_fu_303_p1, "bound4_fu_303_p1");
    sc_trace(mVcdFile, col_0_i_i_i_cast_fu_309_p1, "col_0_i_i_i_cast_fu_309_p1");
    sc_trace(mVcdFile, grp_fu_260_p2, "grp_fu_260_p2");
    sc_trace(mVcdFile, grp_fu_260_ce, "grp_fu_260_ce");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, grp_fu_265_ce, "grp_fu_265_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, bound4_fu_303_p00, "bound4_fu_303_p00");
    sc_trace(mVcdFile, bound4_fu_303_p10, "bound4_fu_303_p10");
#endif

    }
}

PE27::~PE27() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete Systolic_Array_CodEe_U221;
    delete Systolic_Array_CoeOg_U222;
}

void PE27::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln119_fu_313_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(icmp_ln119_fu_313_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(icmp_ln119_fu_313_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(O_inter_1_2_full_n.read(), ap_const_logic_1))) {
        col_0_i_i_i_reg_225 = add_ln119_reg_371.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        col_0_i_i_i_reg_225 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten13_reg_236 = add_ln122_reg_380.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln119_fu_313_p2.read(), ap_const_lv1_1))) {
        indvar_flatten13_reg_236 = ap_const_lv96_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln122_reg_376_pp0_iter2_reg.read()))) {
        tmp_reg_247 = O_temp_10_fu_335_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln119_fu_313_p2.read(), ap_const_lv1_1))) {
        tmp_reg_247 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln119_reg_371 = add_ln119_fu_318_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln122_reg_380 = add_ln122_fu_329_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        and_ln130_reg_357 = and_ln130_fu_281_p2.read();
        p_c_read_reg_342 = p_c_s_dout.read();
        p_chin_read_reg_347 = p_chin_s_dout.read();
        p_k_read_reg_352 = p_k_s_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        bound4_reg_362 = bound4_fu_303_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln122_reg_376 = icmp_ln122_fu_324_p2.read();
        icmp_ln122_reg_376_pp0_iter1_reg = icmp_ln122_reg_376.read();
        icmp_ln122_reg_376_pp0_iter2_reg = icmp_ln122_reg_376_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        tmp_47_reg_390 = In_inter_1_2_dout.read();
        tmp_48_reg_385 = W_inter_1_2_dout.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(and_ln130_reg_357.read(), ap_const_lv1_1))) {
        tmp_4_i_i_i_reg_395 = grp_fu_265_p2.read();
    }
}

void PE27::thread_In_inter_1_2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0))) {
        In_inter_1_2_blk_n = In_inter_1_2_empty_n.read();
    } else {
        In_inter_1_2_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_In_inter_1_2_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        In_inter_1_2_read = ap_const_logic_1;
    } else {
        In_inter_1_2_read = ap_const_logic_0;
    }
}

void PE27::thread_In_inter_1_3_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0))) {
        In_inter_1_3_blk_n = In_inter_1_3_full_n.read();
    } else {
        In_inter_1_3_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_In_inter_1_3_din() {
    In_inter_1_3_din = In_inter_1_2_dout.read();
}

void PE27::thread_In_inter_1_3_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        In_inter_1_3_write = ap_const_logic_1;
    } else {
        In_inter_1_3_write = ap_const_logic_0;
    }
}

void PE27::thread_O_inter_1_2_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        O_inter_1_2_blk_n = O_inter_1_2_full_n.read();
    } else {
        O_inter_1_2_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_O_inter_1_2_din() {
    O_inter_1_2_din = tmp_reg_247.read();
}

void PE27::thread_O_inter_1_2_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(O_inter_1_2_full_n.read(), ap_const_logic_1))) {
        O_inter_1_2_write = ap_const_logic_1;
    } else {
        O_inter_1_2_write = ap_const_logic_0;
    }
}

void PE27::thread_O_temp_10_fu_335_p3() {
    O_temp_10_fu_335_p3 = (!and_ln130_reg_357.read()[0].is_01())? sc_lv<32>(): ((and_ln130_reg_357.read()[0].to_bool())? grp_fu_260_p2.read(): tmp_reg_247.read());
}

void PE27::thread_W_inter_1_2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0))) {
        W_inter_1_2_blk_n = W_inter_1_2_empty_n.read();
    } else {
        W_inter_1_2_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_W_inter_1_2_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        W_inter_1_2_read = ap_const_logic_1;
    } else {
        W_inter_1_2_read = ap_const_logic_0;
    }
}

void PE27::thread_W_inter_2_2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0))) {
        W_inter_2_2_blk_n = W_inter_2_2_full_n.read();
    } else {
        W_inter_2_2_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_W_inter_2_2_din() {
    W_inter_2_2_din = W_inter_1_2_dout.read();
}

void PE27::thread_W_inter_2_2_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        W_inter_2_2_write = ap_const_logic_1;
    } else {
        W_inter_2_2_write = ap_const_logic_0;
    }
}

void PE27::thread_add_ln119_fu_318_p2() {
    add_ln119_fu_318_p2 = (!col_0_i_i_i_reg_225.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(col_0_i_i_i_reg_225.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void PE27::thread_add_ln122_fu_329_p2() {
    add_ln122_fu_329_p2 = (!ap_phi_mux_indvar_flatten13_phi_fu_240_p4.read().is_01() || !ap_const_lv96_1.is_01())? sc_lv<96>(): (sc_biguint<96>(ap_phi_mux_indvar_flatten13_phi_fu_240_p4.read()) + sc_biguint<96>(ap_const_lv96_1));
}

void PE27::thread_add_ln207_1_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        add_ln207_1_loc_blk_n = add_ln207_1_loc_empty_n.read();
    } else {
        add_ln207_1_loc_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_add_ln207_1_loc_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        add_ln207_1_loc_out_blk_n = add_ln207_1_loc_out_full_n.read();
    } else {
        add_ln207_1_loc_out_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_add_ln207_1_loc_out_din() {
    add_ln207_1_loc_out_din = add_ln207_1_loc_dout.read();
}

void PE27::thread_add_ln207_1_loc_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        add_ln207_1_loc_out_write = ap_const_logic_1;
    } else {
        add_ln207_1_loc_out_write = ap_const_logic_0;
    }
}

void PE27::thread_add_ln207_1_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        add_ln207_1_loc_read = ap_const_logic_1;
    } else {
        add_ln207_1_loc_read = ap_const_logic_0;
    }
}

void PE27::thread_add_ln207_3_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        add_ln207_3_loc_blk_n = add_ln207_3_loc_empty_n.read();
    } else {
        add_ln207_3_loc_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_add_ln207_3_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        add_ln207_3_loc_read = ap_const_logic_1;
    } else {
        add_ln207_3_loc_read = ap_const_logic_0;
    }
}

void PE27::thread_and_ln130_fu_281_p2() {
    and_ln130_fu_281_p2 = (icmp_ln130_fu_269_p2.read() & icmp_ln130_10_fu_275_p2.read());
}

void PE27::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void PE27::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[4];
}

void PE27::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[5];
}

void PE27::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void PE27::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[6];
}

void PE27::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void PE27::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void PE27::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_pp0_stage1_01001() {
    ap_block_pp0_stage1_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, W_inter_1_2_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_2_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_3_full_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, W_inter_2_2_full_n.read()))));
}

void PE27::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, W_inter_1_2_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_2_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_3_full_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, W_inter_2_2_full_n.read()))));
}

void PE27::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, W_inter_1_2_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_2_empty_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_3_full_n.read())) || 
  (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, W_inter_2_2_full_n.read()))));
}

void PE27::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read()));
}

void PE27::thread_ap_block_state10_pp0_stage0_iter2() {
    ap_block_state10_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state11_pp0_stage1_iter2() {
    ap_block_state11_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state5_pp0_stage1_iter0() {
    ap_block_state5_pp0_stage1_iter0 = ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, W_inter_1_2_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_2_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, In_inter_1_3_full_n.read())) || (esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, W_inter_2_2_full_n.read())));
}

void PE27::thread_ap_block_state6_pp0_stage2_iter0() {
    ap_block_state6_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state7_pp0_stage0_iter1() {
    ap_block_state7_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state8_pp0_stage1_iter1() {
    ap_block_state8_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_block_state9_pp0_stage2_iter1() {
    ap_block_state9_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void PE27::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(icmp_ln122_fu_324_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void PE27::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln119_fu_313_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void PE27::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void PE27::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void PE27::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void PE27::thread_ap_phi_mux_indvar_flatten13_phi_fu_240_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln122_reg_376.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten13_phi_fu_240_p4 = add_ln122_reg_380.read();
    } else {
        ap_phi_mux_indvar_flatten13_phi_fu_240_p4 = indvar_flatten13_reg_236.read();
    }
}

void PE27::thread_ap_phi_mux_tmp_phi_fu_252_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln122_reg_376_pp0_iter2_reg.read()))) {
        ap_phi_mux_tmp_phi_fu_252_p4 = O_temp_10_fu_335_p3.read();
    } else {
        ap_phi_mux_tmp_phi_fu_252_p4 = tmp_reg_247.read();
    }
}

void PE27::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void PE27::thread_bound4_fu_303_p0() {
    bound4_fu_303_p0 =  (sc_lv<64>) (bound4_fu_303_p00.read());
}

void PE27::thread_bound4_fu_303_p00() {
    bound4_fu_303_p00 = esl_zext<96,64>(bound_fu_290_p2.read());
}

void PE27::thread_bound4_fu_303_p1() {
    bound4_fu_303_p1 =  (sc_lv<32>) (bound4_fu_303_p10.read());
}

void PE27::thread_bound4_fu_303_p10() {
    bound4_fu_303_p10 = esl_zext<96,32>(p_chin_read_reg_347.read());
}

void PE27::thread_bound4_fu_303_p2() {
    bound4_fu_303_p2 = (!bound4_fu_303_p0.read().is_01() || !bound4_fu_303_p1.read().is_01())? sc_lv<96>(): sc_biguint<64>(bound4_fu_303_p0.read()) * sc_biguint<32>(bound4_fu_303_p1.read());
}

void PE27::thread_bound_fu_290_p0() {
    bound_fu_290_p0 =  (sc_lv<32>) (cast_fu_287_p1.read());
}

void PE27::thread_bound_fu_290_p1() {
    bound_fu_290_p1 =  (sc_lv<32>) (cast_fu_287_p1.read());
}

void PE27::thread_bound_fu_290_p2() {
    bound_fu_290_p2 = (!bound_fu_290_p0.read().is_01() || !bound_fu_290_p1.read().is_01())? sc_lv<64>(): sc_biguint<32>(bound_fu_290_p0.read()) * sc_biguint<32>(bound_fu_290_p1.read());
}

void PE27::thread_cast_fu_287_p1() {
    cast_fu_287_p1 = esl_zext<64,32>(p_k_read_reg_352.read());
}

void PE27::thread_col_0_i_i_i_cast_fu_309_p1() {
    col_0_i_i_i_cast_fu_309_p1 = esl_zext<32,31>(col_0_i_i_i_reg_225.read());
}

void PE27::thread_grp_fu_260_ce() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        grp_fu_260_ce = ap_const_logic_1;
    } else {
        grp_fu_260_ce = ap_const_logic_0;
    }
}

void PE27::thread_grp_fu_265_ce() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        grp_fu_265_ce = ap_const_logic_1;
    } else {
        grp_fu_265_ce = ap_const_logic_0;
    }
}

void PE27::thread_icmp_ln119_fu_313_p2() {
    icmp_ln119_fu_313_p2 = (!col_0_i_i_i_cast_fu_309_p1.read().is_01() || !p_c_read_reg_342.read().is_01())? sc_lv<1>(): (sc_bigint<32>(col_0_i_i_i_cast_fu_309_p1.read()) < sc_bigint<32>(p_c_read_reg_342.read()));
}

void PE27::thread_icmp_ln122_fu_324_p2() {
    icmp_ln122_fu_324_p2 = (!ap_phi_mux_indvar_flatten13_phi_fu_240_p4.read().is_01() || !bound4_reg_362.read().is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten13_phi_fu_240_p4.read() == bound4_reg_362.read());
}

void PE27::thread_icmp_ln130_10_fu_275_p2() {
    icmp_ln130_10_fu_275_p2 = (!p_chout_s_dout.read().is_01() || !add_ln207_1_loc_dout.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_chout_s_dout.read()) > sc_bigint<32>(add_ln207_1_loc_dout.read()));
}

void PE27::thread_icmp_ln130_fu_269_p2() {
    icmp_ln130_fu_269_p2 = (!p_r_s_dout.read().is_01() || !add_ln207_3_loc_dout.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_r_s_dout.read()) > sc_bigint<32>(add_ln207_3_loc_dout.read()));
}

void PE27::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln119_fu_313_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void PE27::thread_p_c_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_c_out_blk_n = p_c_out_full_n.read();
    } else {
        p_c_out_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_c_out_din() {
    p_c_out_din = p_c_s_dout.read();
}

void PE27::thread_p_c_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_c_out_write = ap_const_logic_1;
    } else {
        p_c_out_write = ap_const_logic_0;
    }
}

void PE27::thread_p_c_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_c_s_blk_n = p_c_s_empty_n.read();
    } else {
        p_c_s_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_c_s_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_c_s_read = ap_const_logic_1;
    } else {
        p_c_s_read = ap_const_logic_0;
    }
}

void PE27::thread_p_chin_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_chin_out_blk_n = p_chin_out_full_n.read();
    } else {
        p_chin_out_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_chin_out_din() {
    p_chin_out_din = p_chin_s_dout.read();
}

void PE27::thread_p_chin_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_chin_out_write = ap_const_logic_1;
    } else {
        p_chin_out_write = ap_const_logic_0;
    }
}

void PE27::thread_p_chin_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_chin_s_blk_n = p_chin_s_empty_n.read();
    } else {
        p_chin_s_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_chin_s_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_chin_s_read = ap_const_logic_1;
    } else {
        p_chin_s_read = ap_const_logic_0;
    }
}

void PE27::thread_p_chout_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_chout_out_blk_n = p_chout_out_full_n.read();
    } else {
        p_chout_out_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_chout_out_din() {
    p_chout_out_din = p_chout_s_dout.read();
}

void PE27::thread_p_chout_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_chout_out_write = ap_const_logic_1;
    } else {
        p_chout_out_write = ap_const_logic_0;
    }
}

void PE27::thread_p_chout_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_chout_s_blk_n = p_chout_s_empty_n.read();
    } else {
        p_chout_s_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_chout_s_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_chout_s_read = ap_const_logic_1;
    } else {
        p_chout_s_read = ap_const_logic_0;
    }
}

void PE27::thread_p_k_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_k_out_blk_n = p_k_out_full_n.read();
    } else {
        p_k_out_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_k_out_din() {
    p_k_out_din = p_k_s_dout.read();
}

void PE27::thread_p_k_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_k_out_write = ap_const_logic_1;
    } else {
        p_k_out_write = ap_const_logic_0;
    }
}

void PE27::thread_p_k_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_k_s_blk_n = p_k_s_empty_n.read();
    } else {
        p_k_s_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_k_s_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_k_s_read = ap_const_logic_1;
    } else {
        p_k_s_read = ap_const_logic_0;
    }
}

void PE27::thread_p_r_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_r_out_blk_n = p_r_out_full_n.read();
    } else {
        p_r_out_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_r_out_din() {
    p_r_out_din = p_r_s_dout.read();
}

void PE27::thread_p_r_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_r_out_write = ap_const_logic_1;
    } else {
        p_r_out_write = ap_const_logic_0;
    }
}

void PE27::thread_p_r_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_r_s_blk_n = p_r_s_empty_n.read();
    } else {
        p_r_s_blk_n = ap_const_logic_1;
    }
}

void PE27::thread_p_r_s_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
        p_r_s_read = ap_const_logic_1;
    } else {
        p_r_s_read = ap_const_logic_0;
    }
}

void PE27::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void PE27::thread_start_out() {
    start_out = real_start.read();
}

void PE27::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void PE27::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_s_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_1_loc_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_c_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chin_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_chout_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_k_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_r_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, add_ln207_3_loc_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln119_fu_313_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln122_fu_324_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln122_fu_324_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 32 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(O_inter_1_2_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

